"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { backend, BackendProduct } from "@/lib/backend";
import { slugifyProduct } from "@/lib/storage";
import AdminMobileNav from "@/components/AdminMobileNav";

const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const CATEGORIES=["Rações","Brinquedos","Acessórios","Farmácia","Higiene","Outros"];

export default function AdminProdutosPage(){
  const [products,setProducts]=useState<BackendProduct[]>([]);
  const [editing,setEditing]=useState<BackendProduct|null>(null);
  const [name,setName]=useState("");const [category,setCategory]=useState("Rações");const [price,setPrice]=useState("");const [stock,setStock]=useState("0");const [icon,setIcon]=useState("🐾");const [image,setImage]=useState("");const [description,setDescription]=useState("");const [active,setActive]=useState(true);
  const [message,setMessage]=useState("");const [error,setError]=useState("");const [loading,setLoading]=useState(true);

  async function refresh(){setProducts(await backend.products(true));}
  useEffect(()=>{(async()=>{if(backend.configured()){if(!(await backend.session())){window.location.href="/login";return;}const p=await backend.profile();if(!p||p.role==="client"){window.location.href="/";return;}}await refresh();})().catch(e=>setError(e instanceof Error?e.message:"Erro ao carregar produtos.")).finally(()=>setLoading(false));},[]);
  function clearForm(){setEditing(null);setName("");setCategory("Rações");setPrice("");setStock("0");setIcon("🐾");setImage("");setDescription("");setActive(true);}
  function edit(p:BackendProduct){setEditing(p);setName(p.name);setCategory(p.category);setPrice(String(p.price).replace(".",","));setStock(String(p.stock));setIcon(p.icon);setImage(p.image||"");setDescription(p.description);setActive(p.active);window.scrollTo({top:0,behavior:"smooth"});}

  async function submit(e:FormEvent){e.preventDefault();setError("");const numericPrice=Number(price.replace(",","."));const numericStock=Math.max(0,Number(stock)||0);if(!name.trim()||!Number.isFinite(numericPrice)||numericPrice<0)return;
    try{const slug=editing?.slug||slugifyProduct(name)||`produto-${Date.now()}`;await backend.saveProduct({id:editing?.id,slug,name:name.trim(),category,price:numericPrice,stock:numericStock,icon:icon.trim()||"🐾",image:image.trim()||undefined,description:description.trim()||"Produto disponível na Oficina dos Bichos.",active});await refresh();setMessage(editing?"Produto atualizado na loja.":"Produto adicionado à Loja Pet.");clearForm();window.setTimeout(()=>setMessage(""),3000);}catch(e){setError(e instanceof Error?e.message:"Não foi possível salvar o produto.");}}
  async function toggle(p:BackendProduct){try{await backend.saveProduct({...p,active:!p.active});await refresh();}catch(e){setError(e instanceof Error?e.message:"Não foi possível alterar a visibilidade.");}}
  async function remove(p:BackendProduct){if(!window.confirm("Excluir este produto do catálogo?"))return;try{await backend.deleteProduct(p.id||p.slug);await refresh();}catch(e){setError(e instanceof Error?e.message:"Não foi possível excluir o produto.");}}

  return <main className="admin-page min-h-screen bg-slate-50 p-5 md:p-8"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-3"><div><Link href="/admin" className="font-bold teal">‹ Dashboard</Link><h1 className="mt-2 text-4xl font-black">Produtos da <span className="teal">Loja Pet</span></h1><p className="mt-1 text-slate-500">Cadastre produtos, preços, estoque e visibilidade.</p></div><Link href="/loja" className="primary px-5 py-3">Abrir loja do cliente</Link></div>
  {message&&<div className="mt-4 rounded-2xl bg-green-50 p-4 font-bold text-green-700">✓ {message}</div>}{error&&<div className="mt-4 rounded-2xl bg-red-50 p-4 font-bold text-red-700">⚠ {error}</div>}
  <section className="card mt-5 p-5"><div className="flex items-center justify-between gap-3"><h2 className="section-title">{editing?"Editar produto":"Novo produto"}</h2>{editing&&<button onClick={clearForm} className="rounded-xl bg-slate-100 px-4 py-2 font-bold">Cancelar edição</button>}</div><form onSubmit={submit} className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><label><span className="field-label">Nome do produto</span><input className="field" value={name} onChange={e=>setName(e.target.value)} required/></label><label><span className="field-label">Categoria</span><select className="field" value={category} onChange={e=>setCategory(e.target.value)}>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label><label><span className="field-label">Preço (R$)</span><input className="field" inputMode="decimal" placeholder="49,90" value={price} onChange={e=>setPrice(e.target.value)} required/></label><label><span className="field-label">Estoque</span><input className="field" type="number" min="0" value={stock} onChange={e=>setStock(e.target.value)}/></label><label><span className="field-label">Ícone/emoji</span><input className="field" value={icon} onChange={e=>setIcon(e.target.value)}/></label><label><span className="field-label">URL da foto (opcional)</span><input className="field" type="url" value={image} onChange={e=>setImage(e.target.value)} placeholder="https://..."/></label><label className="md:col-span-2 xl:col-span-3"><span className="field-label">Descrição</span><textarea className="field min-h-24" value={description} onChange={e=>setDescription(e.target.value)}/></label><label className="flex items-center gap-3 rounded-2xl bg-slate-50 px-4 py-3"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/><b>Visível na loja</b></label><button className="primary px-6 py-3 md:w-fit">{editing?"Salvar alterações":"＋ Adicionar produto"}</button></form></section>
  <section className="card mt-5 p-4 md:p-5"><div className="flex justify-between gap-3"><h2 className="section-title">Catálogo atual</h2><span className="pill">{products.length} produtos</span></div>{loading?<p className="mt-4 font-bold">Carregando...</p>:<><div className="admin-mobile-only mt-4 space-y-3">{products.map(p=><article key={p.slug} className="admin-mobile-card"><div className="flex items-start gap-3">{p.image?<img src={p.image} alt="" className="h-14 w-14 rounded-2xl object-cover"/>:<div className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-teal-50 text-3xl">{p.icon}</div>}<div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><h3 className="font-black">{p.name}</h3><p className="text-xs text-slate-500">{p.category}</p></div><span className="font-black teal">{money(p.price)}</span></div><div className="mt-3 flex items-center justify-between text-sm"><span>Estoque: <b className={p.stock<=5?"text-red-500":""}>{p.stock}</b></span><button onClick={()=>toggle(p)} className={`rounded-full px-3 py-1 text-xs font-black ${p.active?"bg-green-100 text-green-700":"bg-slate-200 text-slate-600"}`}>{p.active?"Visível":"Oculto"}</button></div></div></div><div className="admin-action-grid mt-3"><button onClick={()=>edit(p)} className="rounded-xl bg-teal-50 px-3 py-2 font-bold teal">Editar</button><button onClick={()=>remove(p)} className="rounded-xl bg-red-50 px-3 py-2 font-bold text-red-600">Excluir</button></div></article>)}</div><div className="admin-desktop-only overflow-x-auto"><table className="mt-4 w-full min-w-[900px] text-left"><thead className="text-sm text-slate-500"><tr><th className="py-3">PRODUTO</th><th>CATEGORIA</th><th>PREÇO</th><th>ESTOQUE</th><th>VISÍVEL</th><th>AÇÕES</th></tr></thead><tbody>{products.map(p=><tr key={p.slug} className="border-t border-slate-100"><td className="py-4"><div className="flex items-center gap-3">{p.image?<img src={p.image} alt="" className="h-12 w-12 rounded-xl object-cover"/>:<span className="text-2xl">{p.icon}</span>}<b>{p.name}</b></div></td><td>{p.category}</td><td className="font-black teal">{money(p.price)}</td><td><span className={p.stock<=5?"font-black text-red-500":"font-bold"}>{p.stock}</span></td><td><button onClick={()=>toggle(p)} className={`rounded-full px-3 py-1 text-xs font-black ${p.active?"bg-green-100 text-green-700":"bg-slate-200 text-slate-600"}`}>{p.active?"Sim":"Não"}</button></td><td><div className="flex gap-2"><button onClick={()=>edit(p)} className="rounded-xl bg-teal-50 px-3 py-2 font-bold teal">Editar</button><button onClick={()=>remove(p)} className="rounded-xl bg-red-50 px-3 py-2 font-bold text-red-600">Excluir</button></div></td></tr>)}</tbody></table></div></>}</section>
  </div><AdminMobileNav/></main>;
}
