"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { backend, BackendOrder } from "@/lib/backend";

const money=(v:number)=>v.toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
const STATUS:[string,string][]=[["pending","Pedido recebido"],["confirmed","Confirmado"],["preparing","Em preparação"],["ready","Pronto"],["out_for_delivery","Saiu para entrega"],["completed","Finalizado"],["cancelled","Cancelado"]];
const label=(s:string)=>STATUS.find(x=>x[0]===s)?.[1]||s;

export default function AdminPedidosPage(){
  const [orders,setOrders]=useState<BackendOrder[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [filter,setFilter]=useState("all");
  async function refresh(){setOrders(await backend.adminOrders())}
  useEffect(()=>{(async()=>{if(backend.configured()){if(!(await backend.session())){window.location.href="/login";return;}const p=await backend.profile();if(!p||p.role==="client"){window.location.href="/";return;}}await refresh()})().catch(e=>setError(e instanceof Error?e.message:"Não foi possível carregar os pedidos.")).finally(()=>setLoading(false))},[]);
  const visible=useMemo(()=>filter==="all"?orders:orders.filter(o=>o.status===filter),[orders,filter]);
  async function change(id:string,status:string){try{await backend.updateOrderStatus(id,status);await refresh()}catch(e){setError(e instanceof Error?e.message:"Não foi possível alterar o status.")}}
  return <main className="min-h-screen bg-slate-50 p-5 md:p-8"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-3"><div><Link href="/admin" className="font-bold teal">‹ Dashboard</Link><h1 className="mt-2 text-4xl font-black">Pedidos da <span className="teal">loja</span></h1><p className="muted mt-1">Acompanhe retirada, entrega, pagamento e andamento dos pedidos.</p></div><select className="field max-w-xs" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todos os status</option>{STATUS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>
  {error&&<div className="mt-4 rounded-2xl bg-red-50 p-4 font-bold text-red-700">⚠ {error}</div>}{loading?<div className="card mt-5 p-5 font-bold">Carregando pedidos...</div>:<div className="mt-5 space-y-4">{visible.map(o=><article key={o.id} className="card p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-black">Pedido #{o.id.slice(0,8).toUpperCase()}</h2><span className="pill">{label(o.status)}</span></div><p className="mt-1 text-sm text-slate-500">{new Date(o.createdAt).toLocaleString("pt-BR")}</p><p className="mt-3"><b>{o.clientName}</b>{o.phone&&<> • {o.phone}</>}</p></div><div className="text-right"><div className="text-sm text-slate-500">Total</div><div className="text-2xl font-black teal">{money(o.total)}</div><div className="mt-1 text-sm">Pagamento: <b>{o.paymentMethod}</b></div></div></div>
  <div className="mt-4 grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">Produtos</h3><div className="mt-2 space-y-2">{o.items.map(i=><div key={i.id} className="flex justify-between gap-3 border-b border-slate-200 pb-2 text-sm"><span><b>{i.quantity}x</b> {i.productName}</span><span>{money(i.unitPrice)} un. • <b>{money(i.unitPrice*i.quantity)}</b></span></div>)}</div></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">Recebimento</h3>{o.deliveryMethod==="entrega"?<div className="mt-2 text-sm"><p className="font-black text-teal-700">Tipo: Entrega</p><p className="mt-2">{o.address?.street}, {o.address?.number}</p><p>{o.address?.neighborhood} • {o.address?.city}</p><p>CEP: {o.address?.cep}</p>{o.address?.complement&&<p>Complemento: {o.address.complement}</p>}{o.address?.reference&&<p>Referência: {o.address.reference}</p>}</div>:<p className="mt-2 font-black text-teal-700">Tipo: Retirada na clínica</p>}</div></div>
  <div className="mt-4"><span className="field-label">Alterar status</span><div className="flex flex-wrap gap-2">{STATUS.map(([v,l])=><button key={v} disabled={o.status===v} onClick={()=>change(o.id,v)} className={`rounded-xl px-3 py-2 text-sm font-black ${v==="cancelled"?"bg-red-50 text-red-600":"bg-slate-100 text-slate-700"} disabled:opacity-40`}>{l}</button>)}</div></div></article>)}{!visible.length&&<div className="card p-6 text-center text-slate-500">Nenhum pedido encontrado.</div>}</div>}</div></main>
}
