"use client";

import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import AdminMobileNav from "@/components/AdminMobileNav";
import { backend,BackendAppointment } from "@/lib/backend";

const statuses=["Confirmado","Em andamento","Concluído","Cancelado"];

export default function AdminAgenda(){
 const [items,setItems]=useState<BackendAppointment[]>([]);const [dateFilter,setDateFilter]=useState("");const [message,setMessage]=useState("");const [error,setError]=useState("");const [loading,setLoading]=useState(true);
 async function refresh(){setItems(await backend.adminAppointments())}
 useEffect(()=>{(async()=>{if(backend.configured()){if(!(await backend.session())){window.location.href="/login";return;}const p=await backend.profile();if(!p||p.role==="client"){window.location.href="/";return;}}await refresh()})().catch(e=>setError(e instanceof Error?e.message:"Erro ao carregar agenda.")).finally(()=>setLoading(false))},[]);
 const visible=useMemo(()=>dateFilter?items.filter(x=>x.date===dateFilter):items,[items,dateFilter]);
 async function reschedule(a:BackendAppointment){const nextDate=window.prompt("Nova data (AAAA-MM-DD):",a.date);if(!nextDate)return;const nextTime=window.prompt("Novo horário (HH:MM):",a.time);if(!nextTime)return;try{setError("");await backend.adminRescheduleAppointment(a.id,nextDate,nextTime);await refresh();setMessage("Agendamento reagendado com sucesso. O cliente recebeu uma notificação.");window.setTimeout(()=>setMessage(""),3500)}catch(e){const msg=e instanceof Error?e.message:"Não foi possível reagendar.";setError(msg.includes("SLOT_UNAVAILABLE")?"Esse novo horário não está disponível para o profissional.":msg)}}
 async function status(id:string,nextStatus:string){try{await backend.setAppointmentStatus(id,nextStatus);await refresh();setMessage(nextStatus==="Cancelado"?"Agendamento cancelado. O horário foi liberado e o cliente foi avisado.":`Status alterado para ${nextStatus}. O cliente recebeu a atualização.`);window.setTimeout(()=>setMessage(""),3500)}catch(e){setError(e instanceof Error?e.message:"Não foi possível alterar o status.")}}
 return <main className="admin-page min-h-screen bg-slate-50 p-5 md:p-8"><div className="mx-auto max-w-7xl"><div className="admin-sticky-tools flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><Link href="/admin" className="font-bold teal">‹ Dashboard</Link><h1 className="mt-2 text-4xl font-black">Agenda <span className="teal">administrativa</span></h1><p className="muted mt-1">Acompanhe e atualize os atendimentos.</p></div><Link href="/admin/horarios" className="primary px-5 py-3 text-center">Gerenciar horários</Link></div>
 {message&&<div className="mt-4 rounded-2xl bg-green-50 p-4 font-bold text-green-700">✓ {message}</div>}{error&&<div className="mt-4 rounded-2xl bg-red-50 p-4 font-bold text-red-700">⚠ {error}</div>}
 <section className="card mt-5 p-4 md:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-end"><label className="flex-1"><span className="field-label">Filtrar por data</span><input type="date" className="field" value={dateFilter} onChange={e=>setDateFilter(e.target.value)}/></label>{dateFilter&&<button className="rounded-xl bg-slate-100 px-4 py-3 font-bold" onClick={()=>setDateFilter("")}>Limpar</button>}<span className="pill self-start sm:self-auto">{visible.length} agendamentos</span></div></section>
 {loading?<div className="card mt-5 p-5 font-bold">Carregando...</div>:<><div className="admin-mobile-only mt-4 space-y-3">{visible.map(a=><article key={a.id} className="admin-mobile-card"><div className="flex items-start justify-between gap-3"><div><p className="text-lg font-black">{a.pet}</p><p className="text-sm text-slate-500">{a.tutor||"—"}</p></div><span className="pill">{a.status}</span></div><div className="mt-3 grid grid-cols-2 gap-3 rounded-2xl bg-slate-50 p-3 text-sm"><div><span className="text-xs font-bold text-slate-400">DATA</span><p className="font-black">{a.date.split("-").reverse().join("/")}</p></div><div><span className="text-xs font-bold text-slate-400">HORÁRIO</span><p className="font-black teal">{a.time}</p></div><div className="col-span-2"><span className="text-xs font-bold text-slate-400">ATENDIMENTO</span><p className="font-bold">{a.service}</p><p className="text-xs text-slate-500">{a.professionalName} • {a.sector}</p></div></div><div className="admin-action-grid mt-3">{a.status!=="Cancelado"&&<button onClick={()=>reschedule(a)} className="rounded-xl bg-teal-50 px-3 py-2 text-xs font-black text-teal-700">Reagendar</button>}{statuses.map(s=><button key={s} disabled={a.status===s} onClick={()=>status(a.id,s)} className={`rounded-xl px-3 py-2 text-xs font-black ${s==="Cancelado"?"bg-red-50 text-red-600":"bg-slate-100 text-slate-700"} disabled:opacity-40`}>{s}</button>)}</div></article>)}{!visible.length&&<div className="card p-6 text-center text-slate-500">Nenhum agendamento encontrado.</div>}</div><section className="card admin-desktop-only mt-5 overflow-x-auto p-5"><table className="w-full min-w-[1100px] text-left"><thead className="text-sm text-slate-500"><tr><th className="py-3">DATA</th><th>HORA</th><th>PET / TUTOR</th><th>SERVIÇO</th><th>PROFISSIONAL</th><th>STATUS</th><th>AÇÕES</th></tr></thead><tbody>{visible.map(a=><tr key={a.id} className="border-t border-slate-100"><td className="py-4">{a.date.split("-").reverse().join("/")}</td><td className="font-black teal">{a.time}</td><td><b>{a.pet}</b><div className="text-sm text-slate-500">{a.tutor||"—"}</div></td><td>{a.service}</td><td>{a.professionalName}<div className="text-xs text-slate-500">{a.sector}</div></td><td><span className="pill">{a.status}</span></td><td><div className="flex flex-wrap gap-2">{a.status!=="Cancelado"&&<button onClick={()=>reschedule(a)} className="rounded-xl bg-teal-50 px-3 py-2 text-xs font-black text-teal-700">Reagendar</button>}{statuses.map(s=><button key={s} disabled={a.status===s} onClick={()=>status(a.id,s)} className={`rounded-xl px-3 py-2 text-xs font-black ${s==="Cancelado"?"bg-red-50 text-red-600":"bg-slate-100 text-slate-700"} disabled:opacity-40`}>{s}</button>)}</div></td></tr>)}</tbody></table></section></>}
 </div><AdminMobileNav/></main>
}
