"use client";

import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import AdminMobileNav from "@/components/AdminMobileNav";
import AdminMobileTopBar from "@/components/AdminMobileTopBar";
import { backend,BackendAppointment,BackendOrder,BackendProduct } from "@/lib/backend";

function todayIso(){const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-${String(now.getDate()).padStart(2,"0")}`}
function appointmentDateTime(a:BackendAppointment){return new Date(`${a.date}T${a.time}:00`).getTime()}

function DashboardSkeleton(){
 return <><div className="admin-stats-grid mt-5 grid grid-cols-2 gap-3 xl:grid-cols-4">{Array.from({length:4}).map((_,i)=><div className="admin-stat" key={i}><div className="skeleton h-9 w-20 rounded-xl"/><div className="skeleton mt-3 h-4 w-16 rounded-lg"/><div className="skeleton mt-2 h-3 w-24 rounded-lg"/></div>)}</div><div className="admin-shortcuts mt-4 grid grid-cols-2 gap-3 md:grid-cols-4">{Array.from({length:4}).map((_,i)=><div className="card admin-shortcut" key={i}><div className="skeleton h-5 w-20 rounded-lg"/></div>)}</div><section className="card admin-upcoming mt-5 p-5"><div className="skeleton h-6 w-52 rounded-lg"/><div className="mt-4 space-y-3">{Array.from({length:2}).map((_,i)=><div className="admin-mobile-card" key={i}><div className="skeleton h-4 w-2/3 rounded-lg"/><div className="skeleton mt-3 h-3 w-1/2 rounded-lg"/><div className="skeleton mt-4 h-4 w-full rounded-lg"/></div>)}</div></section></>
}

export default function AdminPage(){
 const [appts,setAppts]=useState<BackendAppointment[]>([]);const [products,setProducts]=useState<BackendProduct[]>([]);const [orders,setOrders]=useState<BackendOrder[]>([]);const [unread,setUnread]=useState(0);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 useEffect(()=>{(async()=>{if(backend.configured()){if(!(await backend.session())){window.location.href="/login";return;}const profile=await backend.profile();if(!profile||profile.role==="client"){window.location.href="/";return;}}const [a,p,o,n]=await Promise.all([backend.adminAppointments(),backend.products(true),backend.adminOrders(),backend.unreadNotificationCount("admin")]);setAppts(a);setProducts(p);setOrders(o);setUnread(n);})().catch(e=>setError(e instanceof Error?e.message:"Não foi possível carregar o painel.")).finally(()=>setLoading(false))},[]);
 const active=appts.filter(a=>a.status!=="Cancelado");const today=active.filter(a=>a.date===todayIso());const low=useMemo(()=>products.filter(p=>p.active&&p.stock<=5),[products]);const openOrders=orders.filter(o=>!["completed","cancelled"].includes(o.status)).length;
 const upcoming=useMemo(()=>appts.filter(a=>!["Cancelado","Concluído"].includes(a.status)&&appointmentDateTime(a)>=Date.now()).sort((a,b)=>appointmentDateTime(a)-appointmentDateTime(b)),[appts]);
 const menu=[["Dashboard","/admin","🏠"],["Agenda","/admin/agenda","📅"],["Horários","/admin/horarios","🕐"],["Pedidos","/admin/pedidos","📦"],["Produtos","/admin/produtos","🛍️"],["Notificações","/admin/notificacoes","🔔"]];
 const stats=[["📅","Hoje",String(today.length),"atendimentos"],["📦","Pedidos",String(openOrders),"em andamento"],["🔔","Novidades",String(unread),"não lidas"],["⚠️","Estoque",String(low.length),"itens baixos"]];
 return <main className="admin-page min-h-screen bg-slate-50 p-5 md:p-8"><AdminMobileTopBar unread={unread}/><div className="mx-auto grid max-w-[1500px] gap-5 lg:grid-cols-[240px_1fr]"><aside className="card admin-desktop-only h-fit p-5 lg:sticky lg:top-5"><Link href="/" className="text-2xl font-black">🐾 Oficina dos Bichos</Link><div className="mt-6 space-y-2">{menu.map(([label,href,icon],i)=><Link href={href} key={label} className={`flex items-center justify-between rounded-xl px-4 py-3 font-bold ${i===0?"bg-teal-100 text-teal-800":"text-slate-600 hover:bg-slate-50"}`}><span>{icon} {label}</span>{label==="Notificações"&&unread>0&&<span className="rounded-full bg-red-500 px-2 py-0.5 text-xs text-white">{unread}</span>}</Link>)}</div></aside><section className="min-w-0"><header className="admin-dashboard-hero flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div className="min-w-0"><p className="admin-eyebrow text-sm font-black uppercase tracking-[.16em] text-teal-600">Oficina dos Bichos</p><h1 className="admin-page-title text-4xl font-black">Painel <span className="teal">Administrativo</span></h1><p className="muted mt-1">Tudo que a clínica precisa acompanhar hoje.</p></div><div className="admin-hero-actions flex gap-2"><Link href="/admin/notificacoes" className="admin-desktop-only relative h-12 w-12 place-items-center rounded-2xl bg-white shadow-sm">🔔{unread>0&&<span className="absolute -right-1 -top-1 grid h-5 min-w-5 place-items-center rounded-full bg-red-500 px-1 text-[10px] font-black text-white">{unread>9?"9+":unread}</span>}</Link><Link href="/" className="rounded-2xl bg-white px-4 py-3 font-black teal shadow-sm">Ver app</Link></div></header>
 {error&&<div className="mt-4 rounded-2xl bg-red-50 p-4 font-bold text-red-700">⚠ {error}</div>}
 {loading?<DashboardSkeleton/>:<><div className="admin-stats-grid mt-5 grid grid-cols-2 gap-3 xl:grid-cols-4">{stats.map(([icon,label,value,sub])=><div className="admin-stat" key={label}><div className="admin-stat-top"><span className="admin-stat-icon">{icon}</span><span className="admin-stat-value">{value}</span></div><p className="admin-stat-label">{label}</p><p className="admin-stat-sub">{sub}</p></div>)}</div>
 <div className="admin-shortcuts mt-4 grid grid-cols-2 gap-3 md:grid-cols-4"><Link href="/admin/agenda" className="primary admin-shortcut"><span className="text-xl">📅</span><span>Agenda</span></Link><Link href="/admin/pedidos" className="card admin-shortcut"><span className="text-xl">📦</span><span>Pedidos</span></Link><Link href="/admin/horarios" className="card admin-shortcut"><span className="text-xl">🕐</span><span>Horários</span></Link><Link href="/admin/produtos" className="card admin-shortcut"><span className="text-xl">🛍️</span><span>Produtos</span></Link></div>
 <section className="card admin-upcoming mt-5 p-5"><div className="flex items-center justify-between gap-3"><h2 className="section-title">Próximos atendimentos</h2><Link href="/admin/agenda" className="shrink-0 font-bold teal">Ver todos ›</Link></div><div className="admin-mobile-only mt-4 space-y-3">{upcoming.slice(0,6).map(a=><article key={a.id} className="admin-mobile-card"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate font-black">{a.pet} <span className="font-normal text-slate-400">• {a.tutor||"Tutor"}</span></p><p className="mt-1 text-sm text-slate-600">{a.service} • {a.professionalName}</p></div><span className="pill shrink-0">{a.status}</span></div><div className="mt-3 flex items-center justify-between border-t border-slate-100 pt-3"><span className="text-sm font-bold">{a.date.split("-").reverse().join("/")}</span><span className="text-lg font-black teal">{a.time}</span></div></article>)}{!upcoming.length&&<div className="admin-empty-state"><span>📅</span><p>Nenhum atendimento futuro agendado.</p></div>}</div><div className="admin-desktop-only overflow-x-auto"><table className="mt-4 w-full min-w-[820px] text-left"><thead className="text-sm text-slate-500"><tr><th className="py-3">DATA</th><th>HORÁRIO</th><th>PET</th><th>TUTOR</th><th>SERVIÇO</th><th>PROFISSIONAL</th><th>STATUS</th></tr></thead><tbody>{upcoming.slice(0,10).map(row=><tr key={row.id} className="border-t border-slate-100"><td className="py-4">{row.date.split("-").reverse().join("/")}</td><td className="font-black teal">{row.time}</td><td className="font-bold">{row.pet}</td><td>{row.tutor||"—"}</td><td>{row.service}</td><td>{row.professionalName}</td><td><span className="pill">{row.status}</span></td></tr>)}</tbody></table>{!upcoming.length&&<p className="py-8 text-center text-slate-500">Nenhum atendimento futuro agendado.</p>}</div></section></>}
 </section></div><AdminMobileNav/></main>
}
