"use client";

import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import AdminMobileNav from "@/components/AdminMobileNav";
import { backend,BackendAppointment,BackendOrder,BackendProduct } from "@/lib/backend";

function todayIso(){const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}-${String(now.getDate()).padStart(2,"0")}`}

export default function AdminPage(){
 const [appts,setAppts]=useState<BackendAppointment[]>([]);const [products,setProducts]=useState<BackendProduct[]>([]);const [orders,setOrders]=useState<BackendOrder[]>([]);const [unread,setUnread]=useState(0);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 useEffect(()=>{(async()=>{if(backend.configured()){if(!(await backend.session())){window.location.href="/login";return;}const profile=await backend.profile();if(!profile||profile.role==="client"){window.location.href="/";return;}}const [a,p,o,n]=await Promise.all([backend.adminAppointments(),backend.products(true),backend.adminOrders(),backend.unreadNotificationCount("admin")]);setAppts(a);setProducts(p);setOrders(o);setUnread(n);})().catch(e=>setError(e instanceof Error?e.message:"Não foi possível carregar o painel.")).finally(()=>setLoading(false))},[]);
 const active=appts.filter(a=>a.status!=="Cancelado");const today=active.filter(a=>a.date===todayIso());const low=useMemo(()=>products.filter(p=>p.active&&p.stock<=5),[products]);const openOrders=orders.filter(o=>!["completed","cancelled"].includes(o.status)).length;
 const menu=[["Dashboard","/admin","🏠"],["Agenda","/admin/agenda","📅"],["Horários","/admin/horarios","🕐"],["Pedidos","/admin/pedidos","📦"],["Produtos","/admin/produtos","🛍️"],["Notificações","/admin/notificacoes","🔔"]];
 return <main className="admin-page min-h-screen bg-slate-50 p-5 md:p-8"><div className="mx-auto grid max-w-[1500px] gap-5 lg:grid-cols-[240px_1fr]"><aside className="card admin-desktop-only h-fit p-5 lg:sticky lg:top-5"><Link href="/" className="text-2xl font-black">🐾 Oficina dos Bichos</Link><div className="mt-6 space-y-2">{menu.map(([label,href,icon],i)=><Link href={href} key={label} className={`flex items-center justify-between rounded-xl px-4 py-3 font-bold ${i===0?"bg-teal-100 text-teal-800":"text-slate-600 hover:bg-slate-50"}`}><span>{icon} {label}</span>{label==="Notificações"&&unread>0&&<span className="rounded-full bg-red-500 px-2 py-0.5 text-xs text-white">{unread}</span>}</Link>)}</div></aside><section><header className="admin-sticky-tools flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><p className="text-sm font-black uppercase tracking-[.16em] text-teal-600">Oficina dos Bichos</p><h1 className="text-4xl font-black">Painel <span className="teal">Administrativo</span></h1><p className="muted mt-1">Tudo que a clínica precisa acompanhar hoje.</p></div><div className="flex gap-2"><Link href="/admin/notificacoes" className="relative grid h-12 w-12 place-items-center rounded-2xl bg-white shadow-sm">🔔{unread>0&&<span className="absolute -right-1 -top-1 grid h-5 min-w-5 place-items-center rounded-full bg-red-500 px-1 text-[10px] font-black text-white">{unread>9?"9+":unread}</span>}</Link><Link href="/" className="rounded-2xl bg-white px-4 py-3 font-black teal shadow-sm">Ver app</Link></div></header>
 {error&&<div className="mt-4 rounded-2xl bg-red-50 p-4 font-bold text-red-700">⚠ {error}</div>}{loading&&<div className="card mt-5 p-5 font-bold">Carregando dados da clínica...</div>}
 <div className="mt-5 grid grid-cols-2 gap-3 xl:grid-cols-4">{[["📅","Hoje",String(today.length),"atendimentos"],["📦","Pedidos",String(openOrders),"em andamento"],["🔔","Novidades",String(unread),"não lidas"],["⚠️","Estoque",String(low.length),"itens baixos"]].map(([icon,label,value,sub])=><div className="admin-stat" key={label}><div className="flex items-center justify-between"><span className="text-2xl">{icon}</span><span className="text-3xl font-black">{value}</span></div><p className="mt-2 font-black">{label}</p><p className="text-xs text-slate-500">{sub}</p></div>)}</div>
 <div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4"><Link href="/admin/agenda" className="primary flex min-h-20 flex-col justify-center px-4 py-3"><span className="text-xl">📅</span><span className="mt-1 text-sm">Agenda</span></Link><Link href="/admin/pedidos" className="card flex min-h-20 flex-col justify-center p-4 font-black"><span className="text-xl">📦</span><span className="mt-1 text-sm">Pedidos</span></Link><Link href="/admin/horarios" className="card flex min-h-20 flex-col justify-center p-4 font-black"><span className="text-xl">🕐</span><span className="mt-1 text-sm">Horários</span></Link><Link href="/admin/produtos" className="card flex min-h-20 flex-col justify-center p-4 font-black"><span className="text-xl">🛍️</span><span className="mt-1 text-sm">Produtos</span></Link></div>
 <section className="card mt-5 p-5"><div className="flex items-center justify-between gap-3"><h2 className="section-title">Próximos atendimentos</h2><Link href="/admin/agenda" className="font-bold teal">Ver todos ›</Link></div><div className="admin-mobile-only mt-4 space-y-3">{active.slice(0,6).map(a=><article key={a.id} className="admin-mobile-card"><div className="flex items-start justify-between gap-3"><div><p className="font-black">{a.pet} <span className="font-normal text-slate-400">• {a.tutor||"Tutor"}</span></p><p className="mt-1 text-sm text-slate-600">{a.service} • {a.professionalName}</p></div><span className="pill">{a.status}</span></div><div className="mt-3 flex items-center justify-between border-t border-slate-100 pt-3"><span className="text-sm font-bold">{a.date.split("-").reverse().join("/")}</span><span className="text-lg font-black teal">{a.time}</span></div></article>)}{!active.length&&<p className="text-sm text-slate-500">Nenhum atendimento agendado.</p>}</div><div className="admin-desktop-only overflow-x-auto"><table className="mt-4 w-full min-w-[820px] text-left"><thead className="text-sm text-slate-500"><tr><th className="py-3">DATA</th><th>HORÁRIO</th><th>PET</th><th>TUTOR</th><th>SERVIÇO</th><th>PROFISSIONAL</th><th>STATUS</th></tr></thead><tbody>{active.slice(0,10).map(row=><tr key={row.id} className="border-t border-slate-100"><td className="py-4">{row.date.split("-").reverse().join("/")}</td><td className="font-black teal">{row.time}</td><td className="font-bold">{row.pet}</td><td>{row.tutor||"—"}</td><td>{row.service}</td><td>{row.professionalName}</td><td><span className="pill">{row.status}</span></td></tr>)}</tbody></table></div></section>
 </section></div><AdminMobileNav/></main>
}
